apiVersion: apps/v1 
kind: Deployment
metadata:
  name: udacity-deployment
spec:
  selector:
    matchLabels:
      app: udacity-devops-project
  replicas: 2 # tells deployment to run 2 pods matching the template
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

  template:
    metadata:
      labels:
        app: udacity-devops-project
    spec:
      containers:
      - name: udacity-devops-project
        image: colince/udacity-capstone
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
